on:
  push:
    branches:
      - dev
    
jobs:
  start_on_dev:
      runs-on: ubuntu-latest
      steps:
         - name: call custom deploy action
           id: deploy
           uses: jlmorris3827/deployment-actions@test-branch
           with: 
               username: user1
               password: pass1
           
         - name: show action results
           run: echo "RESULT {{ steps.deploy.outputs.result }}"
         
        
